name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            NEXT_PUBLIC_BACKAPI=${{ secrets.NEXT_PUBLIC_BACKAPI }}
            NEXT_PUBLIC_YANDEX_REDIRECT=${{ secrets.NEXT_PUBLIC_YANDEX_REDIRECT }}
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_TAG }}
